use anyhow::{bail, Context, Result};
use std::{collections::BTreeMap, env, fs};

fn main() -> Result<()> {
    let mut args = env::args().skip(1);
    let command = args.next().unwrap_or_default();
    let path = args.next().context("missing spec.aix")?;
    let raw = fs::read_to_string(path)?;
    let doc = parse_ir(&raw)?;
    match command.as_str() {
        "eval" => {
            let x = read_named_i64(&mut args, "--x")?;
            let result = read_named_i64(&mut args, "--result")?;
            let ok = ensures(&doc)
                .iter()
                .all(|e| eval_bool(e, x, result).unwrap_or(false));
            println!("{}", if ok { "SATISFIES" } else { "VIOLATES" });
            if !ok {
                std::process::exit(2);
            }
        }
        "smt" => print!("{}", emit_smt(&doc)?),
        _ => bail!("usage: axiom-solver <eval|smt> spec.aix [--x N --result N]"),
    }
    Ok(())
}

fn read_named_i64(args: &mut impl Iterator<Item = String>, expected: &str) -> Result<i64> {
    let flag = args.next().context("missing flag")?;
    if flag != expected {
        bail!("expected {expected}, got {flag}");
    }
    Ok(args.next().context("missing numeric value")?.parse()?)
}

fn parse_ir(raw: &str) -> Result<BTreeMap<String, String>> {
    let mut lines = raw.lines();
    if lines.next() != Some("AXIOM-IR/1") {
        bail!("bad IR header");
    }
    let mut map = BTreeMap::new();
    for line in lines.filter(|l| !l.trim().is_empty()) {
        let (k, v) = line.split_once('=').context("invalid IR line")?;
        map.insert(k.to_owned(), v.to_owned());
    }
    Ok(map)
}

fn ensures(doc: &BTreeMap<String, String>) -> Vec<String> {
    doc.iter()
        .filter(|(k, _)| k.starts_with("ensures."))
        .map(|(_, v)| v.clone())
        .collect()
}

fn eval_bool(expr: &str, x: i64, result: i64) -> Result<bool> {
    let expr = expr.trim();
    if let Some((a, b)) = split_top(expr, "||") {
        return Ok(eval_bool(a, x, result)? || eval_bool(b, x, result)?);
    }
    if let Some((a, b)) = split_top(expr, "&&") {
        return Ok(eval_bool(a, x, result)? && eval_bool(b, x, result)?);
    }
    for op in ["==", "!=", ">=", "<=", ">", "<"] {
        if let Some((a, b)) = split_top(expr, op) {
            let a = eval_int(a, x, result)?;
            let b = eval_int(b, x, result)?;
            return Ok(match op {
                "==" => a == b,
                "!=" => a != b,
                ">=" => a >= b,
                "<=" => a <= b,
                ">" => a > b,
                "<" => a < b,
                _ => unreachable!(),
            });
        }
    }
    if expr == "true" {
        return Ok(true);
    }
    if expr == "false" {
        return Ok(false);
    }
    bail!("unsupported boolean expression: {expr}")
}

fn eval_int(expr: &str, x: i64, result: i64) -> Result<i64> {
    let e = expr.trim().trim_matches(|c| c == '(' || c == ')').trim();
    match e {
        "x" => Ok(x),
        "result" => Ok(result),
        "-x" => Ok(x.wrapping_neg()),
        _ => Ok(e.parse()?),
    }
}

fn split_top<'a>(expr: &'a str, op: &str) -> Option<(&'a str, &'a str)> {
    let mut depth = 0i32;
    let bytes = expr.as_bytes();
    let opb = op.as_bytes();
    let mut i = 0usize;
    while i + opb.len() <= bytes.len() {
        match bytes[i] as char {
            '(' => depth += 1,
            ')' => depth -= 1,
            _ => {}
        }
        if depth == 0 && &bytes[i..i + opb.len()] == opb {
            return Some((&expr[..i], &expr[i + opb.len()..]));
        }
        i += 1;
    }
    None
}

fn emit_smt(doc: &BTreeMap<String, String>) -> Result<String> {
    let min = doc.get("domain.min").context("missing domain.min")?;
    let max = doc.get("domain.max").context("missing domain.max")?;
    let mut out = String::from("; Generated by axiom-solver v0.1\n(set-logic QF_LIA)\n(declare-const x Int)\n(declare-const result Int)\n");
    out.push_str(&format!("(assert (and (>= x {min}) (<= x {max})))\n"));
    for e in ensures(doc) {
        out.push_str("; TODO translator: ");
        out.push_str(&e);
        out.push('\n');
    }
    out.push_str("(check-sat)\n(get-model)\n");
    Ok(out)
}
