// SPDX-FileCopyrightText: 2026 Ivan Zorin <creator@localzet.com> (Localzet contributions)
// SPDX-License-Identifier: MIT
use anyhow::{bail, Context, Result};
use std::{collections::BTreeMap, env, fs};

fn main() -> Result<()> {
    let mut args = env::args().skip(1);
    if args.next().as_deref() != Some("smt") {
        bail!("usage: axiom-solver smt spec.aix [--program-expr EXPR]");
    }
    let path = args.next().context("missing spec.aix")?;
    let doc = parse_ir(&fs::read_to_string(path)?)?;

    let mut program_expr = None;
    if let Some(flag) = args.next() {
        if flag != "--program-expr" {
            bail!("unexpected flag: {flag}");
        }
        program_expr = Some(args.next().context("missing program expression")?);
    }

    print!("{}", emit_smt(&doc, program_expr.as_deref())?);
    Ok(())
}

fn parse_ir(raw: &str) -> Result<BTreeMap<String, String>> {
    let mut lines = raw.lines();
    if lines.next() != Some("AXIOM-IR/2") {
        bail!("bad IR header");
    }
    let mut map = BTreeMap::new();
    for line in lines.filter(|line| !line.trim().is_empty()) {
        let (key, value) = line.split_once('=').context("invalid IR line")?;
        map.insert(key.to_owned(), value.to_owned());
    }
    Ok(map)
}

fn expressions(doc: &BTreeMap<String, String>, prefix: &str) -> Vec<String> {
    doc.iter()
        .filter(|(key, _)| key.starts_with(prefix) && key.ends_with(".expr"))
        .map(|(_, value)| value.clone())
        .collect()
}

fn emit_smt(doc: &BTreeMap<String, String>, program_expr: Option<&str>) -> Result<String> {
    let input = doc.get("input.0.name").context("missing input name")?;
    let output = doc.get("output.name").context("missing output name")?;
    let mut out = String::from("; Generated by axiom-solver v0.2.0\n(set-logic QF_LIA)\n");
    out.push_str(&format!("(declare-const {input} Int)\n"));
    out.push_str(&format!("(declare-const {output} Int)\n"));

    let kind = doc
        .get(&format!("domain.{input}.kind"))
        .context("missing domain kind")?;
    if kind == "range" {
        let min = &doc[&format!("domain.{input}.min")];
        let max = &doc[&format!("domain.{input}.max")];
        out.push_str(&format!(
            "(assert (and (>= {input} {min}) (<= {input} {max})))\n"
        ));
    }

    for expr in expressions(doc, "requires.") {
        out.push_str(&format!("(assert {})\n", to_smt_bool(&expr)?));
    }
    if let Some(expr) = program_expr {
        out.push_str(&format!("(assert (= {output} {}))\n", to_smt_int(expr)?));
    }

    let ensures = expressions(doc, "ensures.");
    if !ensures.is_empty() {
        out.push_str("; Search for a counterexample to at least one postcondition.\n");
        out.push_str("(assert (not (and\n");
        for expr in ensures {
            out.push_str(&format!("  {}\n", to_smt_bool(&expr)?));
        }
        out.push_str(")))\n");
    }
    out.push_str("(check-sat)\n(get-model)\n");
    Ok(out)
}

fn to_smt_bool(expr: &str) -> Result<String> {
    let expr = strip_outer(expr.trim());
    if expr == "true" || expr == "false" {
        return Ok(expr.to_owned());
    }
    if let Some((left, right)) = split_top(expr, "||") {
        return Ok(format!(
            "(or {} {})",
            to_smt_bool(left)?,
            to_smt_bool(right)?
        ));
    }
    if let Some((left, right)) = split_top(expr, "&&") {
        return Ok(format!(
            "(and {} {})",
            to_smt_bool(left)?,
            to_smt_bool(right)?
        ));
    }
    for op in ["==", "!=", ">=", "<=", ">", "<"] {
        if let Some((left, right)) = split_top(expr, op) {
            let smt_op = match op {
                "==" => "=",
                "!=" => "distinct",
                other => other,
            };
            return Ok(format!(
                "({smt_op} {} {})",
                to_smt_int(left)?,
                to_smt_int(right)?
            ));
        }
    }
    bail!("unsupported boolean expression: {expr}")
}

fn to_smt_int(expr: &str) -> Result<String> {
    let expr = strip_outer(expr.trim());
    if let Some(rest) = expr.strip_prefix('-') {
        if !rest.is_empty() {
            return Ok(format!("(- {})", to_smt_int(rest)?));
        }
    }
    if let Some((left, right)) = split_top(expr, "+") {
        return Ok(format!("(+ {} {})", to_smt_int(left)?, to_smt_int(right)?));
    }
    if let Some((left, right)) = split_top(expr, "-") {
        return Ok(format!("(- {} {})", to_smt_int(left)?, to_smt_int(right)?));
    }
    if expr
        .chars()
        .all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '-')
    {
        return Ok(expr.to_owned());
    }
    bail!("unsupported integer expression: {expr}")
}

fn strip_outer(expr: &str) -> &str {
    let mut current = expr.trim();
    loop {
        if current.starts_with('(') && current.ends_with(')') && outer_pair_covers_all(current) {
            current = current[1..current.len() - 1].trim();
        } else {
            return current;
        }
    }
}

fn outer_pair_covers_all(expr: &str) -> bool {
    let mut depth = 0i32;
    for (index, ch) in expr.char_indices() {
        match ch {
            '(' => depth += 1,
            ')' => {
                depth -= 1;
                if depth == 0 && index + ch.len_utf8() != expr.len() {
                    return false;
                }
            }
            _ => {}
        }
    }
    depth == 0
}

fn split_top<'a>(expr: &'a str, op: &str) -> Option<(&'a str, &'a str)> {
    let bytes = expr.as_bytes();
    let op_bytes = op.as_bytes();
    let mut depth = 0i32;
    let mut index = 0usize;
    while index + op_bytes.len() <= bytes.len() {
        match bytes[index] as char {
            '(' => depth += 1,
            ')' => depth -= 1,
            _ => {}
        }
        if depth == 0 && &bytes[index..index + op_bytes.len()] == op_bytes {
            if op == "-" && index == 0 {
                index += 1;
                continue;
            }
            return Some((&expr[..index], &expr[index + op_bytes.len()..]));
        }
        index += 1;
    }
    None
}

#[cfg(test)]
mod tests {
    use super::to_smt_bool;

    #[test]
    fn translates_abs_postcondition() {
        assert_eq!(
            to_smt_bool("result == x || result == -x").unwrap(),
            "(or (= result x) (= result (- x)))"
        );
    }
}
